### ISSUE TITLE
Rename minified lib to use *.min.js

### ISSUE THREAD

**Issue by rodrigopinto** [raphamorim/angular-drag-n-drop#4]
What do you think about rename the lib to include *.min.js.

**Comment by raphamorim** [comment]
Makes sense, updated: https://github.com/raphamorim/angular-drag-n-drop/commit/4585f50d4af2586ca7f3af1d0105985b6851427a

Still missing add uncompressed file in root, and in src folder apply a better organization. Separating by directives, factories [...] per files

**Comment by rodrigopinto** [comment]
Nice, if you want I can get it and send PR.

**Comment by raphamorim** [comment]
If you can, would be grateful :)

**Comment by raphamorim** [comment]
Closed in ac35d8c24ea77c6aa48b248be7c999882a68efc4 ~ ac35d8c24ea77c6aa48b248be7c999882a68efc4
